
[addressbooks]
#[[all]]
#path = /var/lib/radicale/collections/collection-root/linn/e69f0f24-109c-4b17-ae55-2961ce17a4b8/
#type = discover
[[google]]
path = ~/.local/share/linn/contacts/google-contacts/google-book/
type = discover
[[mutt]]
path = ~/.local/share/linn/contacts/radicale/radicalebook/
type = discover
[[disroot]]
path = ~/.local/share/linn/contacts/disroot/contacts
type = discover
